### ISSUE TITLE
how do i run the server and use the gpt

### ISSUE THREAD

**Issue by xmoufyy** [xtekky/chatgpt-clone#22]
i did it and it says this
Running on port 1337
 * Serving Flask app 'server.app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 and then my ip and stuff but how do iuse the clone

**Comment by xtekky** [comment]
you should see a localhost address, so visit http://localhost:1337 on your device
the site is not working at the moment though

**Comment by xmoufyy** [comment]
thanks @xtekky sorry new to python and stuff only know lua
