### ISSUE TITLE
FATAL ERROR 

### ISSUE THREAD

**Issue by flavioaguirre222** [xtekky/chatgpt-clone#23]
WHEN I TRY TO INSTALL USING: pip install -r requirements.txt

Fatal error in launcher: "Unable to create process using '"C:\Users\flavi\chatgpt-clone\venv\Scripts\python.exe"  "C:\WINDOWS\system32\chatgpt-clone\venv\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado."

**Comment by AgentSonji** [comment]
Try navigating to the folder where you installed this. Looks like pip is looking for "requirements.txt'" in whatever folder you are in when you run the command. Hence why you get a file not found error

**Comment by flavioaguirre222** [comment]
> Try navigating to the folder where you installed this. Looks like pip is looking for "requirements.txt'" in whatever folder you are in when you run the command. Hence why you get a file not found error

I already test it, im at the folder there is a requirements.txt there, but the error continues, what can i do i quite lost here

**Comment by AgentSonji** [comment]
Np! Please mark this as closed when you can.
