### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by witwall** [xtekky/chatgpt-clone#3]
## conversions
- double confirm when delete
- support output 

## theme
easy switch black to white.

**Comment by xtekky** [comment]
what do u mean by support output ? 

Theme changer is comming soon

**Comment by witwall** [comment]
output  conversions

**Comment by QuartzWarrior** [comment]
> output conversions

Do you mean like exporting conversations?

**Comment by witwall** [comment]
you got it.

**Comment by xtekky** [comment]
added to the to do list
