### ISSUE TITLE
Remember user preferences

### ISSUE THREAD

**Issue by alfonmga** [xtekky/chatgpt-clone#4]
Hi,

Currently, user preferences (like model preference) are not persisted.
I find myself all the time changing it back to my preferred model.

We could store the user's preference on localStorage.

<img width="401" alt="Screenshot 2023-04-21 at 19 28 11" src="https://user-images.githubusercontent.com/9363272/233698504-be2ed884-a210-4db6-96ad-d8edaf2e195c.png">

**Comment by xtekky** [comment]
alright will look at it
