### ISSUE TITLE
When I send message to it, it send this to me 

### ISSUE THREAD

**Issue by YeoZIllnard-Unique** [xtekky/chatgpt-clone#40]
{"_action":"_ask","error":"an error occurred HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))","success":false}

**Comment by flavioaguirre222** [comment]
Dude, its already exists an issue about it, please read all issues before posting. Thank you.
One last thing, please, delete this issue

**Comment by SabeBarker** [comment]
see issue #79
