### ISSUE TITLE
Access local file directories

### ISSUE THREAD

**Issue by edwardsaunders7** [xtekky/chatgpt-clone#6]
Is there any way to implement file directory access into this when running locally? I am interested in providing the bot with context and pre-existing files to use as a framework. 

https://github.com/mayooear/gpt4-pdf-chatbot-langchain enables reading from PDF files, however I wonder if it's possible to provide it with a directory consisting of .txt, .docx, .py, etc files that it can then use as a pre-existing context

**Comment by xtekky** [comment]
added to to do list
