### ISSUE TITLE
open_api_key Error

### ISSUE THREAD

**Issue by hamidjalili59** [xtekky/chatgpt-clone#66]
I get this error when I try to run the program
self.openai_key = os.environ["OPENAI_API_KEY"] or config['openai_key']
![Untitled](https://user-images.githubusercontent.com/42936283/235256024-c802af50-c6bb-4365-981d-035e376270bf.png)

**Comment by MrZname** [comment]
you shold make this commands before script run
SET OPENAI_API_KEY=your key
SET OPENAI_API_BASE=https://api.openai.com
