### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by MrZname** [xtekky/chatgpt-clone#67]
![image](https://user-images.githubusercontent.com/91285240/235257360-65026756-7830-4565-82ed-82d551d42db3.png)
selfhosted version 
after send message to bot i see in cli message(screenshot)
and bot don't give answer

**Comment by Lanthanum1** [comment]
I got the same error, and when I use gpt3.5, I can recieve the answer, but in the back end termial,an error occurs:
Expecting value: line 1 column 2 (char 1)
<traceback object at 0x0000014687D3FF40>
list index out of range
None

**Comment by sup3r93** [comment]
same

**Comment by xtekky** [comment]
Hi, please check you configured the openai api auth settings right

**Comment by MrZname** [comment]
ist it right?
eport SET OPENAI_API_KEY=my_k
export SET OPENAI_API_BASE=https://api.openai.com/
