### ISSUE TITLE
A black bar is coming at the bottom of the screen in large screen devices

### ISSUE THREAD

**Issue by Zeus2480** [xtekky/chatgpt-clone#70]
My device screen size is 17 inches and a black bar is visible at the bottom of the screen
![image](https://user-images.githubusercontent.com/89025631/235282892-477bfa51-7abb-4cc3-a383-630d33ca349f.png)

I have fixed this issue.
![image](https://user-images.githubusercontent.com/89025631/235282937-086cac42-9c43-4c6d-8a35-917374d0162d.png)
Kindly accept my PR.

**Comment by xtekky** [comment]
did, thank you very much
